# Generated by Django 6.0.3 on 2026-03-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
